typography_spectrum: 0.08807474537752569
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.15625042584724724
  lightness: 0.21174286492168903
  saturation: 0.5521462594624609
  rhythmicContrast: 0.1295149235520512
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.679308912018314
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: vivian
  email: vivian@vaviking.co.nz
  url: www.tiniki.co.nz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e76d3922-8dca-4f3b-ac63-7633d42d7fb3.svg
name: testingwebsite
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Chocolate milkshake
    id: 229d30b7-0b18-4928-976b-bc14278f4c50
    type: content
favicon: null
title: NICEBAR-奶昔吧
description: health is easy to make
purpose: []
